### ISSUE TITLE
Any updates on the progression of this idea?

### ISSUE THREAD

**Issue by RTippin** [trongate/p-plus-plus#1]
Curious what exactly this entails.

**Comment by trongate** [comment]
Well, unfortunately the name is taken.  So, I'd have to come up with a new name.  Also, I have concerns about whether I may have bitten off more than I can chew.  Do you have C++ expertise at all?

**Comment by RTippin** [comment]
No experience with c++ outside of some confined work on arduio's and LED lighting design 😆 

Sounds like too much to chew though. We'd need to be proficient with reading/comprehending the php source if we wanted to break off from it, but making a language sounds exciting 😄
